CREATE TABLE dbo.DropdownOptions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Category NVARCHAR(100) NOT NULL,
    Value NVARCHAR(200) NOT NULL,
    SortOrder INT NOT NULL DEFAULT(0),
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EmployeeId NVARCHAR(50) NOT NULL,
    FullName NVARCHAR(200) NOT NULL,
    Email NVARCHAR(200) NOT NULL,
    Department NVARCHAR(200) NULL,
    Title NVARCHAR(200) NULL,
    Location NVARCHAR(200) NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Programs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ProgramCode NVARCHAR(50) NOT NULL,
    ProgramName NVARCHAR(200) NOT NULL,
    Description NVARCHAR(500) NULL,
    IsActive BIT NOT NULL DEFAULT(1),
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.UarRequests (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    RequestNumber NVARCHAR(50) NOT NULL,
    SubmittedOn DATETIME2 NOT NULL,
    EmployeeNameChange NVARCHAR(20) NULL,
    Company NVARCHAR(200) NOT NULL,
    EmployeeFirstName NVARCHAR(100) NOT NULL,
    EmployeeMiddleName NVARCHAR(50) NOT NULL,
    EmployeeLastName NVARCHAR(100) NOT NULL,
    JobTitle NVARCHAR(200) NOT NULL,
    DesiredEffectiveDate NVARCHAR(50) NULL,
    RequestorPhoneNumber NVARCHAR(50) NOT NULL,
    EmployeeStatus NVARCHAR(100) NOT NULL,
    EmployeeType NVARCHAR(100) NULL,
    TransferFromProgram NVARCHAR(20) NULL,
    LeaveOfAbsence NVARCHAR(20) NULL,
    RegionName NVARCHAR(200) NULL,
    Program1 NVARCHAR(200) NOT NULL,
    Program2 NVARCHAR(200) NULL,
    Program3 NVARCHAR(200) NULL,
    OtherPrograms NVARCHAR(MAX) NULL,
    EmployeeDeviceTypes NVARCHAR(MAX) NULL,
    OtherDeviceType NVARCHAR(200) NULL,
    HrRepresentativeName NVARCHAR(200) NULL,
    SubmitForApproval NVARCHAR(20) NULL,
    Status NVARCHAR(100) NOT NULL,
    AuthorizedApprover NVARCHAR(200) NOT NULL,
    ProgramAdministrator NVARCHAR(200) NOT NULL,
    RdoApprover NVARCHAR(200) NULL,
    RejectionReason NVARCHAR(MAX) NULL,
    EmailAccount NVARCHAR(20) NULL,
    AccountEnableDisable NVARCHAR(50) NULL,
    ForwardingEmailAddress NVARCHAR(200) NULL,
    AssignedAccountUsername NVARCHAR(200) NULL,
    Office365License NVARCHAR(200) NULL,
    AdditionalMicrosoftProducts NVARCHAR(MAX) NULL,
    CreateEmailGroups NVARCHAR(20) NULL,
    SharePointSiteUrl NVARCHAR(500) NULL,
    SharePointSiteDescription NVARCHAR(200) NULL,
    ExistingEmailGroups NVARCHAR(MAX) NULL,
    AdditionalSharepointAccess NVARCHAR(MAX) NULL,
    NetworkSharedDrives NVARCHAR(MAX) NULL,
    TopAccess NVARCHAR(20) NULL,
    KronosAccessTypes NVARCHAR(MAX) NULL,
    KronosAccessDetails NVARCHAR(MAX) NULL,
    LawsonAccess NVARCHAR(20) NULL,
    AdditionalLawsonAccess NVARCHAR(MAX) NULL,
    MileageAccess NVARCHAR(20) NULL,
    ComericaBankingAccess NVARCHAR(20) NULL,
    TrustRepPayeeAccess NVARCHAR(20) NULL,
    QuickbooksAccess NVARCHAR(20) NULL,
    CoWorkerAccess NVARCHAR(20) NULL,
    AdditionalHrFinanceAccess NVARCHAR(MAX) NULL,
    OrderConnectAccess NVARCHAR(20) NULL,
    CaminarAccess NVARCHAR(20) NULL,
    AvatarAccess NVARCHAR(20) NULL,
    AdverseEventSupervisorAccess NVARCHAR(20) NULL,
    AdverseEventAdditionalProgramAccess NVARCHAR(20) NULL,
    BusinessIntelligenceRole NVARCHAR(200) NULL,
    AdverseEventNonEmployeeAccess NVARCHAR(20) NULL,
    TelehealthAccess NVARCHAR(20) NULL,
    NextTelehealthSession NVARCHAR(100) NULL,
    AdditionalComments NVARCHAR(MAX) NULL,
    PharmericaAccess NVARCHAR(20) NULL,
    PharmericaUserRole NVARCHAR(200) NULL,
    PharmericaUsername NVARCHAR(200) NULL,
    CallCenterAccess NVARCHAR(20) NULL,
    AdobeSignAccount NVARCHAR(20) NULL,
    CopilotLicense NVARCHAR(20) NULL,
    SmartsheetLicense NVARCHAR(20) NULL,
    EFax NVARCHAR(20) NULL
);
